export const REQUEST_SIGN_IN = 'REQUEST_SIGN_IN';
export const SIGN_IN_SUCCESSFUL = 'SIGN_IN_SUCCESSFUL';
export const REQUEST_SIGN_UP = 'REQUEST_SIGN_UP';
export const SIGN_UP_SUCCESSFUL = 'SIGN_UP_SUCCESSFUL';
export const REQUEST_LOG_OUT = 'REQUEST_LOG_OUT';
export const LOG_OUT_SUCCESSFUL = 'LOG_OUT_SUCCESSFUL';
